// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logStirling2State_C
RawVector logStirling2State_C(int n, Nullable<RawVector> state);
RcppExport SEXP _logStirling2_logStirling2State_C(SEXP nSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Nullable<RawVector> >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(logStirling2State_C(n, state));
    return rcpp_result_gen;
END_RCPP
}
// logStirling2Row_C
NumericVector logStirling2Row_C(int n, Nullable<RawVector> state);
RcppExport SEXP _logStirling2_logStirling2Row_C(SEXP nSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Nullable<RawVector> >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(logStirling2Row_C(n, state));
    return rcpp_result_gen;
END_RCPP
}
// logStirling2All_C
NumericVector logStirling2All_C(int n, Nullable<RawVector> state);
RcppExport SEXP _logStirling2_logStirling2All_C(SEXP nSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Nullable<RawVector> >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(logStirling2All_C(n, state));
    return rcpp_result_gen;
END_RCPP
}
// logStirling2Mult_C
NumericVector logStirling2Mult_C(IntegerVector n, Nullable<RawVector> state);
RcppExport SEXP _logStirling2_logStirling2Mult_C(SEXP nSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< Nullable<RawVector> >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(logStirling2Mult_C(n, state));
    return rcpp_result_gen;
END_RCPP
}
// create_ld_state_C
RawVector create_ld_state_C(CharacterVector x);
RcppExport SEXP _logStirling2_create_ld_state_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ld_state_C(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_logStirling2_logStirling2State_C", (DL_FUNC) &_logStirling2_logStirling2State_C, 2},
    {"_logStirling2_logStirling2Row_C", (DL_FUNC) &_logStirling2_logStirling2Row_C, 2},
    {"_logStirling2_logStirling2All_C", (DL_FUNC) &_logStirling2_logStirling2All_C, 2},
    {"_logStirling2_logStirling2Mult_C", (DL_FUNC) &_logStirling2_logStirling2Mult_C, 2},
    {"_logStirling2_create_ld_state_C", (DL_FUNC) &_logStirling2_create_ld_state_C, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_logStirling2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
