# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logStirling2State_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2State_C`, n, state)
}

logStirling2Row_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2Row_C`, n, state)
}

logStirling2All_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2All_C`, n, state)
}

logStirling2Mult_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2Mult_C`, n, state)
}

create_ld_state_C <- function(x) {
    .Call(`_logStirling2_create_ld_state_C`, x)
}

#' Second-Order Eulerian Numbers
#'
#' Calculates the exact values of the second-order Eulerian numbers 
#' \eqn{\langle\langle n, k \rangle\rangle} for a fixed row \eqn{n} and all 
#' \eqn{k \in \{0, \dots, n-1\}}.
#'
#' @param n A positive integer specifying the row index.
#' @return A \code{bigz} vector of length \code{n} containing the sequence 
#' \eqn{\langle\langle n, 0 \rangle\rangle, \langle\langle n, 1 \rangle\rangle, \dots, \langle\langle n, n-1 \rangle\rangle}.
#' @export
Eulerian2All <- function(n) {
    .Call(`_logStirling2_Eulerian2All`, n)
}

#' Stirling Numbers of the Second Kind
#'
#' Calculates the exact values of the Stirling numbers of the second kind 
#' \eqn{S(n, k)} for a fixed \eqn{n} and all \eqn{k \in \{1, \dots, n\}}.
#'
#' @param n A positive integer specifying the set size.
#' @return A \code{bigz} vector of length \code{n} containing the Stirling 
#' numbers of the second kind \eqn{S(n, 1), S(n, 2), \dots, S(n, n)}.
#' @export
Stirling2All <- function(n) {
    .Call(`_logStirling2_Stirling2All`, n)
}

