# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logStirling2State_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2State_C`, n, state)
}

logStirling2Row_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2Row_C`, n, state)
}

logStirling2All_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2All_C`, n, state)
}

logStirling2Mult_C <- function(n, state = NULL) {
    .Call(`_logStirling2_logStirling2Mult_C`, n, state)
}

create_ld_state_C <- function(x) {
    .Call(`_logStirling2_create_ld_state_C`, x)
}

